// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `io.github.copper.loader.Loader`
extension type Loader._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'io/github/copper/loader/Loader');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Loader> type = $Loader$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Loader() {
    final _$$classRef = _class.reference;
    return _new$(_$$classRef.pointer, _id_new$.pointer).object<Loader>();
  }

  static final _id_launch = _class.staticMethodId(
    r'launch',
    r'(Ljava/lang/String;Landroid/content/Context;[Ljava/lang/String;)V',
  );

  static final _launch =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void launch(java.lang.String loaderPath, android.content.Context activityContext, java.lang.String[] args)`
  ///
  /// Starts the loader through MindustryActivity, passing the loader jar and its arguments.
  static void launch(
    jni$_.JString? loaderPath,
    Context? activityContext,
    jni$_.JArray<jni$_.JString?>? args,
  ) {
    final _$$classRef = _class.reference;
    final _$loaderPath = loaderPath?.reference ?? jni$_.jNullReference;
    final _$activityContext =
        activityContext?.reference ?? jni$_.jNullReference;
    final _$args = args?.reference ?? jni$_.jNullReference;
    _launch(
      _$$classRef.pointer,
      _id_launch.pointer,
      _$loaderPath.pointer,
      _$activityContext.pointer,
      _$args.pointer,
    ).check();
  }

  static final _id_build = _class.staticMethodId(
    r'build',
    r'(Ljava/lang/String;[Ljava/lang/String;)V',
  );

  static final _build =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void build(java.lang.String loaderPath, java.lang.String[] args)`
  ///
  /// Runs {@code ArtBuilder} on the device to build the dex cache.
  static void build(
    jni$_.JString? loaderPath,
    jni$_.JArray<jni$_.JString?>? args,
  ) {
    final _$$classRef = _class.reference;
    final _$loaderPath = loaderPath?.reference ?? jni$_.jNullReference;
    final _$args = args?.reference ?? jni$_.jNullReference;
    _build(
      _$$classRef.pointer,
      _id_build.pointer,
      _$loaderPath.pointer,
      _$args.pointer,
    ).check();
  }
}

final class $Loader$Type$ extends jni$_.JType<Loader> {
  @jni$_.internal
  const $Loader$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/github/copper/loader/Loader;';
}

/// from: `io.github.copper.bridge.Bridge`
///
/// Placeholder entry of the bridge: a real JVM, instead of the copper loader on ART.
///
/// The counterpart of io.github.copper.loader.Loader\#launch, and deliberately the same
/// shape: the caller builds the whole argument vector and names the jar, this only hands both to the
/// placeholder activity, and the component factory turns it into the activity the bridge builds.
/// What the run needs - the game jar, the data and cache folders, the JVM, arc's native libraries -
/// is the argument vector's business, not this class's.
///
extension type Bridge._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'io/github/copper/bridge/Bridge');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Bridge> type = $Bridge$Type$();
  static final _id_launch = _class.staticMethodId(
    r'launch',
    r'(Ljava/lang/String;Landroid/content/Context;[Ljava/lang/String;)V',
  );

  static final _launch =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void launch(java.lang.String bridgePath, android.content.Context activityContext, java.lang.String[] args)`
  ///
  /// Starts the bridge through MindustryActivity, passing the bridge jar and its arguments.
  static void launch(
    jni$_.JString? bridgePath,
    Context? activityContext,
    jni$_.JArray<jni$_.JString?>? args,
  ) {
    final _$$classRef = _class.reference;
    final _$bridgePath = bridgePath?.reference ?? jni$_.jNullReference;
    final _$activityContext =
        activityContext?.reference ?? jni$_.jNullReference;
    final _$args = args?.reference ?? jni$_.jNullReference;
    _launch(
      _$$classRef.pointer,
      _id_launch.pointer,
      _$bridgePath.pointer,
      _$activityContext.pointer,
      _$args.pointer,
    ).check();
  }
}

final class $Bridge$Type$ extends jni$_.JType<Bridge> {
  @jni$_.internal
  const $Bridge$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/github/copper/bridge/Bridge;';
}

/// from: `io.github.copper.SystemInfo`
///
/// Device memory, straight from the activity manager.
///
/// Extracted from {@code io.github.copper.loader.Loader} when the bridge path arrived: nothing
/// about it is loader-specific, and it is read while deciding how much heap a game run may ask for.
///
extension type SystemInfo._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'io/github/copper/SystemInfo');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemInfo> type = $SystemInfo$Type$();
  static final _id_getMemoryInfo = _class.staticMethodId(
    r'getMemoryInfo',
    r'(Landroid/content/Context;)Lio/github/copper/SystemInfo$MemoryInfo;',
  );

  static final _getMemoryInfo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public io.github.copper.SystemInfo$MemoryInfo getMemoryInfo(android.content.Context applicationContext)`
  /// The returned object must be released after use, by calling the [release] method.
  ///
  /// Get native memory info.
  static SystemInfo$MemoryInfo? getMemoryInfo(Context? applicationContext) {
    final _$$classRef = _class.reference;
    final _$applicationContext =
        applicationContext?.reference ?? jni$_.jNullReference;
    return _getMemoryInfo(
      _$$classRef.pointer,
      _id_getMemoryInfo.pointer,
      _$applicationContext.pointer,
    ).object<SystemInfo$MemoryInfo?>();
  }

  static final _id_getHeapMemoryInfo = _class.staticMethodId(
    r'getHeapMemoryInfo',
    r'(Landroid/content/Context;)Lio/github/copper/SystemInfo$HeapMemoryInfo;',
  );

  static final _getHeapMemoryInfo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public io.github.copper.SystemInfo$HeapMemoryInfo getHeapMemoryInfo(android.content.Context applicationContext)`
  /// The returned object must be released after use, by calling the [release] method.
  ///
  /// Get art heap memory info.
  static SystemInfo$HeapMemoryInfo? getHeapMemoryInfo(
    Context? applicationContext,
  ) {
    final _$$classRef = _class.reference;
    final _$applicationContext =
        applicationContext?.reference ?? jni$_.jNullReference;
    return _getHeapMemoryInfo(
      _$$classRef.pointer,
      _id_getHeapMemoryInfo.pointer,
      _$applicationContext.pointer,
    ).object<SystemInfo$HeapMemoryInfo?>();
  }
}

final class $SystemInfo$Type$ extends jni$_.JType<SystemInfo> {
  @jni$_.internal
  const $SystemInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/github/copper/SystemInfo;';
}

/// from: `io.github.copper.SystemInfo$MemoryInfo`
///
/// Wrapper of android.app.ActivityManager.MemoryInfo
extension type SystemInfo$MemoryInfo._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'io/github/copper/SystemInfo$MemoryInfo',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemInfo$MemoryInfo> type =
      $SystemInfo$MemoryInfo$Type$();
}

extension SystemInfo$MemoryInfo$$Methods on SystemInfo$MemoryInfo {
  static final _id_availMem = SystemInfo$MemoryInfo._class.instanceFieldId(
    r'availMem',
    r'J',
  );

  /// from: `public long availMem`
  core$_.int get availMem =>
      _id_availMem.getNullable(this, jni$_.jlong.type) as core$_.int;

  /// from: `public long availMem`
  set availMem(core$_.int value) =>
      _id_availMem.set(this, jni$_.jlong.type, value);

  static final _id_lowMemory = SystemInfo$MemoryInfo._class.instanceFieldId(
    r'lowMemory',
    r'Z',
  );

  /// from: `public boolean lowMemory`
  core$_.bool get lowMemory =>
      _id_lowMemory.getNullable(this, jni$_.jboolean.type) as core$_.bool;

  /// from: `public boolean lowMemory`
  set lowMemory(core$_.bool value) =>
      _id_lowMemory.set(this, jni$_.jboolean.type, value);

  static final _id_threshold = SystemInfo$MemoryInfo._class.instanceFieldId(
    r'threshold',
    r'J',
  );

  /// from: `public long threshold`
  core$_.int get threshold =>
      _id_threshold.getNullable(this, jni$_.jlong.type) as core$_.int;

  /// from: `public long threshold`
  set threshold(core$_.int value) =>
      _id_threshold.set(this, jni$_.jlong.type, value);

  static final _id_totalMem = SystemInfo$MemoryInfo._class.instanceFieldId(
    r'totalMem',
    r'J',
  );

  /// from: `public long totalMem`
  core$_.int get totalMem =>
      _id_totalMem.getNullable(this, jni$_.jlong.type) as core$_.int;

  /// from: `public long totalMem`
  set totalMem(core$_.int value) =>
      _id_totalMem.set(this, jni$_.jlong.type, value);
}

final class $SystemInfo$MemoryInfo$Type$
    extends jni$_.JType<SystemInfo$MemoryInfo> {
  @jni$_.internal
  const $SystemInfo$MemoryInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/github/copper/SystemInfo$MemoryInfo;';
}

/// from: `io.github.copper.SystemInfo$HeapMemoryInfo`
///
/// Heap memory info of ART.
extension type SystemInfo$HeapMemoryInfo._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'io/github/copper/SystemInfo$HeapMemoryInfo',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemInfo$HeapMemoryInfo> type =
      $SystemInfo$HeapMemoryInfo$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory SystemInfo$HeapMemoryInfo() {
    final _$$classRef = _class.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
    ).object<SystemInfo$HeapMemoryInfo>();
  }
}

extension SystemInfo$HeapMemoryInfo$$Methods on SystemInfo$HeapMemoryInfo {
  static final _id_normalSize = SystemInfo$HeapMemoryInfo._class
      .instanceFieldId(r'normalSize', r'I');

  /// from: `public int normalSize`
  ///
  /// dalvik.vm.heapgrowthlimit, unit: megabytes
  core$_.int get normalSize =>
      _id_normalSize.getNullable(this, jni$_.jint.type) as core$_.int;

  /// from: `public int normalSize`
  ///
  /// dalvik.vm.heapgrowthlimit, unit: megabytes
  set normalSize(core$_.int value) =>
      _id_normalSize.set(this, jni$_.jint.type, value);

  static final _id_largeSize = SystemInfo$HeapMemoryInfo._class.instanceFieldId(
    r'largeSize',
    r'I',
  );

  /// from: `public int largeSize`
  ///
  /// dalvik.vm.heapsize, unit: megabytes
  core$_.int get largeSize =>
      _id_largeSize.getNullable(this, jni$_.jint.type) as core$_.int;

  /// from: `public int largeSize`
  ///
  /// dalvik.vm.heapsize, unit: megabytes
  set largeSize(core$_.int value) =>
      _id_largeSize.set(this, jni$_.jint.type, value);
}

final class $SystemInfo$HeapMemoryInfo$Type$
    extends jni$_.JType<SystemInfo$HeapMemoryInfo> {
  @jni$_.internal
  const $SystemInfo$HeapMemoryInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/github/copper/SystemInfo$HeapMemoryInfo;';
}

/// from: `android.content.Context`
///
/// WARNING: Context is a stub. To generate bindings for this class, include
/// android.content.Context in your config's classes list.
///
extension type Context._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Context> type = $Context$Type$();
}

final class $Context$Type$ extends jni$_.JType<Context> {
  @jni$_.internal
  const $Context$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/Context;';
}
